# Generated by Django 5.2.6 on 2025-10-23 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrequest',
            old_name='owner',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectrequest',
            unique_together={('project', 'member')},
        ),
    ]
