# Generated by Django 5.2.6 on 2025-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_owner_projectrequest_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='message',
            field=models.CharField(default='I am interested in joining this project', max_length=250),
            preserve_default=False,
        ),
    ]
