# Generated by Django 5.2.8 on 2025-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmembers_projectrequestrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembers',
            name='message',
            field=models.CharField(default='I am interested in joining this project', max_length=400),
        ),
        migrations.AddField(
            model_name='projectrequestrejected',
            name='message',
            field=models.CharField(default='I am interested in joining this project', max_length=400),
        ),
        migrations.AlterField(
            model_name='projectlead',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='message',
            field=models.CharField(max_length=400),
        ),
    ]
